package com.example.EmployeeApp1.entity;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Version;

//Employee needs to be converted into table and this class can persist
@Entity
public class Employee {
    //ID tells employeeid is primary key and employee id will be autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    int empid;
    String empname;
    String empcity;




    public Employee(int empid , String empname , String empcity) {
        this.empid = empid;
        this.empname = empname;
        this.empcity = empcity;
    }

    public Employee(){

    }

    public int getEmpid() {
        return empid;
    }

    public void setEmpid(int empid) {
        this.empid = empid;
    }

    public String getEmpname() {
        return empname;
    }

    public void setEmpname(String empname) {
        this.empname = empname;
    }

    public String getEmpcity() {
        return empcity;
    }

    public void setEmpcity(String empcity) {
        this.empcity = empcity;
    }


}

